# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-22 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='country',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='state',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
